package com.cytech.fenetres;

import javafx.fxml.FXML;


import javafx.scene.control.TextField;

import com.cytech.Main;


import javafx.event.ActionEvent;



import javafx.scene.control.Button;

 

public class PageConnexionUtilisateurController {
	
    @SuppressWarnings("unused")
    private Main main;
	@FXML
	private TextField codePrive;
	@FXML
	private TextField motDePasseUtilisateur;
	@FXML
	private Button boutonRetour;

    // Event Listener on Button.onAction
    @FXML
    public void ConnexionBoutonUtilisateur(ActionEvent event) {
        // TODO Autogenerated
    }
    // Event Listener on Button.onAction
    @FXML
    public void boutonInscription(ActionEvent event) {
        // TODO Autogenerated
    }
    public void setMain(Main main) {
        this.main = main;

    }
	// Event Listener on Button[#boutonRetour].onAction
	@FXML
	public void retourBoutonPageConnexionUtilisateur(ActionEvent event) {
		if (main != null) {
            main.afficherAccueil(); // Utilise ta méthode centralisée
        } else {
            System.err.println("ERREUR : main vaut null !");
        }
	}
}
