package com.cytech.fenetres;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class PageAjoutPersonneArbreController {
	@FXML
	private TableView adherentTable;
	@FXML
	private TableColumn nomColonne;
	@FXML
	private TableColumn prenomColonne;
	@FXML
	private TableColumn RelationColonne;
	@FXML
	private TableColumn NaissanceColonne;
	@FXML
	private TableColumn mortColonne;

	// Event Listener on Button.onAction
	@FXML
	public void BoutonAjouterPersonne(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void BoutonRetour(ActionEvent event) {
		// TODO Autogenerated
	}
}
