package com.cytech.fenetres;

import javafx.fxml.FXML;	


import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import com.cytech.Main;

import javafx.event.ActionEvent;

public class PageConnexionAdministrateurController {
	private Main main;
	@FXML
	private TextField codePrive;
	@FXML
	private TextField motDePasseAdministrateur;
	@FXML
	private Button boutonRetour;

	// Event Listener on Button.onAction
	@FXML
	public void ConnexionBoutonAdministrateur(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#boutonRetour].onAction
	@FXML
	public void retourBoutonPageConnexionUtilisateur(ActionEvent event) {
	    if (main != null) {
	        main.afficherAccueil(); // Utilise ta méthode centralisée
	    } else {
	        System.err.println("ERREUR : main vaut null !");
	    }
	}
	public void setMain(Main main) {
	    this.main = main;
	}
}
