package com.cytech.fenetres;

import javafx.fxml.FXML;

import com.cytech.Main;

import javafx.event.ActionEvent;

public class PagePrincipaleUtilisateurController {
	
	private int codePrive;
	
	private Main main;
	
	public void setMain(Main main) {
        this.main = main;

    }
	
	public void setCodePrive(int codePrive) {
		this.codePrive = codePrive;
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void modifierProfilUtilisateur(ActionEvent event) {
		main.afficherProfilUtilisateurController(codePrive);
	}
	// Event Listener on Button.onAction
	@FXML
	public void DeconnectionUtilisateur(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void ajouterPersonneArbreUtilisateur(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void EnvoyerRessource(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void genererArbreGraphiquement(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void genererArbreConsole(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void faireDesRequetesArbresUtilisateur(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void consulterAnnuaireAdherents(ActionEvent event) {
		// TODO Autogenerated
	}
	
 
}
