package com.cytech.fenetres;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class PageChangementMDPController {
	@FXML
	private PasswordField motDePasseChanger;

	// Event Listener on Button.onAction
	@FXML
	public void ValiderChangementMDP(ActionEvent event) {
		// TODO Autogenerated
	}
}
